### ISSUE TITLE
Design test cases

### ISSUE THREAD

**Issue by meeroslaph** [meeroslaph/friday#2]
> Implement a UI test that goes through our [sales funnel](https://hello.friday.de/). Your test should stop when you have to enter your birth date (Wann wurdest du geboren?).

> We ask that your test will pick at least three different car brands, each brand with three different cars.

**Tasks**:
- [x] Design 9 test cases (3 brands x 3 cars).
- [x] Each test should finish with an assertion that `Wann wurdest du geboren?` input is displayed.
- [x] Add negative scenarios.
